### ISSUE TITLE
Audio Not Working in Emulator

### ISSUE THREAD

**Issue by HartLabs** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#112]
The audio does not appear to be working through the thumby.py api in emulator. It works through use of the polysynth.py library.

The issue was confirmed by 2 other users on the discord.

SaurRun from the arcade does not play audio in the emulator (thumby.py).
TinyFreddy from the arcade does play audio in the emulator (polysynth.py).

```
import thumby
thumby.audio.play(261, 1000)
```

Makes no sound.

**Comment by TinyCircuits** [comment]
This is fixed in https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/commit/84185046af6b10f11d099ea8f76bcafa17713775
