### ISSUE TITLE
Files downloaded from Thumby start with console output?

### ISSUE THREAD

**Issue by Timendus** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#23]
Hey there! Awesome work on both the Thumby and the code editor 😄

Whenever I open a (text) file from my Thumby (double click on a file in the filesystem panel), the file is prepended with this text:

```
w REPL; CTRL-B to exit
>OK
```

This looks like some superfluous console output to me. It also seems to mess up binary files.

Because Python files load with these extra characters, the emulator doesn't want to run them (syntax error, obviously) and I have to remove them manually, which is an inconvenience.

I'm using Google Chrome on MacOS 12.3.1.

Feedback from JasonTC on Discord:
> When the editor gets file data from the Thumby it does so through the REPL. The raw REPL is used to run temporary code to get that data from the Thumby. For some reason if you have a lot of files on your Thumby this occurs, but I think it is at least related to the string returned over REPL to get the filesystem structure.

I can confirm that I have "a lot" of files on my Thumby, I added around 40 or so to the stock Thumby.

**Comment by jmtinycircuits** [comment]
This may be fixed with this: https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/pull/32

**Comment by masonova1** [comment]
Haven't seen any update on this. Good to close, or not?
