### ISSUE TITLE
Add invert() to thumbyGraphics class

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#40]
Extend the display API by breaking out `invert()` from ssd1306.

**Comment by masonova1** [comment]
We don't want to expose hardware `invert` for the time being, because monochrome pixel inversion is trivial to do in software and avoids reliance on particular hardware features.

**Comment by ace-dent** [comment]
Thanks for reviewing. I think HW is easier than SW solution ... but ok. :-)
Is there a reason to keep this (and related) HW shortcuts in `SSD1306` then?
(BTW - I'm looking at the API design for the Arduboy2 library, as a reference point).
