### ISSUE TITLE
Add Upload progress bar to 'filesystem'

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#46]
When uploading file(s) it would be nice to see a progress bar, as per saving files.
It is reassuring that the action is working.
Thanks.

**Comment by ace-dent** [comment]
Also, when Thumby is disconnected (often after 'Fast Execute'), disable 'Upload' or alert the User.
Currently the Upload will just silently fail.

**Comment by jmtinycircuits** [comment]
Agreed. These are some of the uglier issues.

I would really like the fix these.
