### ISSUE TITLE
Integrate grayscale support

### ISSUE THREAD

**Issue by aroidzap** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#47]
Please integrate https://github.com/Timendus/thumby-grayscale into official Thumby lib.

**Comment by masonova1** [comment]
The community is having integration problems with newer revisions. Even if the newer revisions did allow for it, the features present in the grayscale library are the product of some very delicate and hardware-specific tunings that we can't guarantee uniform support for over time, and it would be a little unwieldy for the typical user to dial it in manually.

**Comment by aroidzap** [comment]
Couldn't we just add some "experimental grayscale" setting in settings? Every app using grayscale could fallback to regular B/W.

**Comment by masonova1** [comment]
If art assets were made to be displayed in grayscale, and grayscale isn't supported, I'm not sure it's sufficient for many artists to just quantize the grayscale sprites -- I'm worried that doing this would practically mean asking many grayscale game developers to make another set of B/W assets, just in case a particular Thumby won't support grayscale.
