### ISSUE TITLE
busy waiting

### ISSUE THREAD

**Issue by isaacbernat** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#5]
Hi, is "busy waiting" the recommended approach to read user input? I was looking at `Annelid.py` which I got the impression served as kind of tutorial and saw this:
https://github.com/TinyCircuits/tinycircuits.github.io/blob/95a4e5fcc758addc9bdb0b3831498eb3c2234ab8/ThumbyGames/Games/Annelid/Annelid.py#L38-L42

Therefore, I used a similar approach for my own game, but I am worried this could drain battery more than necessary. 
```python
def wait_press(c=getcharinputNew()):
    while(c is None):
        c = getcharinputNew()
    return c
```
What are your thoughts? Thanks.

**references:**
- busy waiting: https://en.wikipedia.org/wiki/Busy_waiting
- my game: https://github.com/isaacbernat/tinymem/blob/main/tinymem.py

**Comment by jmtinycircuits** [comment]
You could use interrupts if you wanted, but that is not built into the API.

I have nothing to say about battery, I'm not sure how much it changes the power consumption compared to interrupts.
