### ISSUE TITLE
OLED GDDRAM is not cleared on initialisation

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#52]
### Problem:  
When working with a customised `main.py`, we cannot rely on the screen buffer overwriting the OLED onboard 'Graphic Display Data RAM' (GDDRAM). This can lead to the unexpected result of showing random data on first boot, or restoring the last image after a reset.
Data persists after power cycling On `0xAF` / Off (sleep screen) `0xAE`, and also Reset (toggling GPIO pin 20) does *not* clear the GDDRAM. This makes sense for some applications; it allows quick resume from sleep without the MCU needing to resend the last screen. 

This function was originally provided with `self.fill(0)` [lines](https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/blob/6c2c18af087254be715221fa34ec505e285cdba9/ThumbyGames/lib/ssd1306.py#L22-L23) (now commented out/ removed).

### Proposed solution:  
Zero the OLED RAM whenever we initialise the display:
- Add a `clear()` function to SSD1306.py that sets the first 360 bytes of GDDRAM =`0x00`. 
- Add `clear()` as the last step in the `init_display()` function.

Note: I have a working code solution and can provide a PR, if this approach is acceptable. It could be argued that clearing the GDDRAM could happen at various points- I just went for the lowest level controller.

**Comment by masonova1** [comment]
This makes sense to me. If you want to do a PR, I'll take it; Otherwise, I can implement as well. Clearing on-init seems to be the most sane option here.

**Comment by ace-dent** [comment]
This solution may be sub-optimal. 
It relies on overwriting the MCU buffer then copying the buffer into the OLED GDDRAM.
There may be a situation where we want to init the OLED and keep the buffer intact (or vice versa).

**Comment by masonova1** [comment]
Reopened to see if this has any way of impacting the emulator - this may not be necessary there. Are there any examples of persistent OLED garbage through restart for the emulator?

**Comment by ace-dent** [comment]
+1
I like your [fix](https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/blob/82623150d21430d63b4993b46e03efedf73c700b/ThumbyGames/lib/ssd1306.py#L21-L22); short and sweet! No need to add to the emulator (I would guess it initialises with a zero filled array).

**Comment by masonova1** [comment]
Sounds good. Closing for now.
