### ISSUE TITLE
thumbySaves.py calls missing method

### ISSUE THREAD

**Issue by dan5sch** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#54]
In commit ae5e822f55a10a5ac41180c4ec613dea96db6515, the `write()` method of `SavesClass` was renamed to `save()`, but the line below wasn't updated accordingly. This code is only reached if a save file is corrupted, which is likely why this wasn't caught.

https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/blob/6c2c18af087254be715221fa34ec505e285cdba9/ThumbyGames/lib/thumbySaves.py#L73

**Comment by masonova1** [comment]
Fixed. Thanks!
