### ISSUE TITLE
request to add shorthand to access the framebuffer easier

### ISSUE THREAD

**Issue by Xyvir** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#74]
I recommend adding the following line to the thumbyGraphics `__init__`
 `self.buffer = self.display.buffer`

this will allow you to access the buffer from your game file by calling

`thumby.display.buffer`

instead of the currently required

`thumby.display.display.buffer`

it's a bit more intuitive IMO

-Tyler

**Comment by masonova1** [comment]
Just implemented this on my fork. It needs to be a `memoryview` or duck typing can't quite figure out it's a reference.

**Comment by Xyvir** [comment]
Cool, thanks!
